### ISSUE TITLE
Hard-coded TargetFrameworkVersion on ProjectGeneration

### ISSUE THREAD

**Issue by leandiez** [needle-mirror/com.unity.ide.visualstudio#1]
Hi! I-m sorry if this is not the right place to report this.
I'm having trouble setting up the last .NET Core version and enabling Intellisense and other features on VSC for Unity.

Searching on Google some people have discovered that this is related to the ProjectGeneration.cs of this Package that is hardcoding the FrameworkVersion to 4.7.1. 
This have been discused here:

https://gamedev.stackexchange.com/questions/166401/use-a-different-target-framework-version-in-a-unity-c-project-other-than-4-6
https://forum.unity.com/threads/how-to-change-vscodes-targetframeworkversion.599476/

Would be possible to obtain this version of the .NET Framework version installed on the PC? Or at least put a setting to configure this.

Thanks in advance!
Regards ;)

**Comment by marwie** [comment]
Hello, please [report this to Unity directly](https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-) (we're not officially associated with Unity so this report will not reach the right people unfortunately)
